### ISSUE TITLE
error solution JSON

### ISSUE THREAD

**Issue by juarez15** [etherealxx/volatile-concentration-localux-colab#36] opened 2023-08-11 21:47 UTC
If the play button is given again, everything loads normally, only you can't get options like before...I love this community, hopefully the error can be solved, it can also be used
![arregggggg](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/139187850/13046351-0708-4173-bdf9-58f3fa1af107)

**Comment by etherealxx** [comment] 2023-08-12 03:51
working on it!

**Comment by etherealxx** [comment] 2023-08-12 04:21
Hi @juarez15👋 I fixed the error by bumping the gradio version to 3.37.0. Please check the latest August 12 version and close this issue if the problem is solved🙏

https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/main/volatile_concentration_localux_colab.ipynb

Also thanks for using my colab, means a lot😊

**Closed** 2023-08-19 03:52 UTC
