### ISSUE TITLE
Something went wrong Unexpected end of JSON input

### ISSUE THREAD

**Issue by vinMoreiraHenrique** [etherealxx/volatile-concentration-localux-colab#34] opened 2023-08-11 17:13 UTC
When i click the big orange "use model" button, it shows this error message: "Something went wrong
Unexpected end of JSON input"

**Comment by just-shinya** [comment] 2023-08-11 20:45
same here v.v

**Comment by etherealxx** [comment] 2023-08-12 03:51
working on it!

**Comment by etherealxx** [comment] 2023-08-12 04:20
Hi @vinMoreiraHenrique, @just-shinya👋 I fixed the error by bumping the gradio version to 3.37.0. Please check the latest August 12 version and close this issue if the problem is solved🙏

https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/main/volatile_concentration_localux_colab.ipynb

**Closed** 2023-08-12 13:58 UTC
